const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const {node,document,marked}=require('./text-dom.cjs');
const s=fs.readFileSync(__dirname+'/../dist/index.html','utf8').match(/<script>\n([\s\S]*?)<\/script>/)[1];
const ctx=vm.createContext({document,Intl});vm.runInContext(s.slice(s.indexOf('function sidewaysRanges'),s.indexOf('// Measure actual')),ctx);
const text='「……」――── 12月3日 2026年 Bloom Garden party A組 ... --';
const runs=ctx.typesetRuns(text);assert.equal(runs.map(r=>r.text).join(''),text);
assert.equal(runs.find(r=>r.text==='12').kind,'tcy');
assert.equal(runs.find(r=>r.text==='3').kind,'upright-digits');
assert.equal(runs.find(r=>r.text==='2026').kind,'upright-digits');
assert.equal(runs.find(r=>r.text==='Bloom Garden party').kind,'latin-words');
assert.equal(runs.find(r=>r.text==='A').kind,'latin-single');
assert.equal(runs.find(r=>r.text==='…').kind,'vertical-symbol');
assert.ok(!ctx.boundaries('あ12い').includes(2));
const el=node();ctx.appendTypeset(el,text,0,[{start:2,end:18}]);assert.equal(el.textContent,text);assert.equal(marked(el),text.slice(2,18));
console.log('Vertical typography preserves source text, selection offsets and highlighted numeric/symbol runs.');

const rules=ctx.typesetRuns('前――後');assert.equal(rules.filter(r=>r.kind==='vertical-rule').length,1);assert.equal(rules.find(r=>r.kind==='vertical-rule').text,'――');
const ruleNode=node();ctx.appendTypeset(ruleNode,'――',0,[{start:1,end:2}]);assert.equal(ruleNode.children.length,1);assert.equal(ruleNode.children[0].style.height,'2.11em');assert.equal(ruleNode.textContent,'――');assert.equal(marked(ruleNode),'―');
console.log('Consecutive rules use one continuous drawing box and retain partial highlight offsets.');

const marker='￢⊥',wrapped='前￢⊥安倍晋三￢⊥後',wrappedRuns=ctx.typesetRuns(wrapped);
const html=fs.readFileSync(__dirname+'/../dist/index.html','utf8');
assert.match(html,/\.page-text \.sideways-text\{text-orientation:sideways;-webkit-text-orientation:sideways/);
assert.match(html,/\.page-text \.writing-marker\{display:none!important\}/);
assert.equal(wrappedRuns.map(r=>r.text).join(''),wrapped);
assert.equal(wrappedRuns.filter(r=>r.kind==='writing-marker').map(r=>r.text).join(''),marker+marker);
assert.equal(wrappedRuns.find(r=>r.kind==='sideways-text').text,'安倍晋三');
const wrappedBoundaries=ctx.boundaries(wrapped),openAt=wrapped.indexOf(marker),closeAt=wrapped.lastIndexOf(marker);
assert.ok(!wrappedBoundaries.includes(openAt+1));assert.ok(!wrappedBoundaries.includes(closeAt+1));
assert.ok(wrappedBoundaries.includes(openAt+marker.length+1),'The sideways text can still wrap across pages.');
const wrappedEl=node();ctx.appendTypeset(wrappedEl,wrapped,0,[{start:3,end:7}]);
assert.equal(wrappedEl.textContent,wrapped);assert.equal(marked(wrappedEl),'安倍晋三');
assert.ok(wrappedEl.children.some(child=>child.className==='sideways-text'));
assert.equal(wrappedEl.children.filter(child=>child.className==='writing-marker').length,2);
const partial=wrapped.slice(3,5),partialEl=node();ctx.appendTypeset(partialEl,partial,3,[],wrapped);
assert.equal(partialEl.textContent,partial);assert.equal(partialEl.children[0].className,'sideways-text');
console.log('￢⊥ markers hide their delimiters, rotate enclosed Japanese text, and preserve pagination and highlight offsets.');

const rubySource='前[[漢字]]<<かんじ>>後と[[12月]]<<じゅうにがつ>>',rubyRuns=ctx.typesetRuns(rubySource);
assert.match(html,/\.page-text ruby\{ruby-position:over;ruby-align:space-around\}/);
assert.equal(rubyRuns.map(r=>r.text).join(''),rubySource);
assert.equal(rubyRuns.filter(r=>r.kind==='writing-marker').map(r=>r.text).join('|'),'[[|]]<<|>>|[[|]]<<|>>');
assert.equal(rubyRuns.filter(r=>r.kind==='ruby-text').map(r=>r.text).join('|'),'かんじ|じゅうにがつ');
assert.equal(rubyRuns.find(r=>r.text==='12').kind,'tcy');
const rubyBoundaries=ctx.boundaries(rubySource),rubyStart=rubySource.indexOf('[['),rubyEnd=rubySource.indexOf('>>')+2;
assert.ok(rubyBoundaries.includes(rubyStart)&&rubyBoundaries.includes(rubyEnd));
assert.ok(rubyBoundaries.every(i=>i<=rubyStart||i>=rubyEnd),'Ruby is never split across pages.');
const rubyEl=node();ctx.appendTypeset(rubyEl,rubySource,0,[{start:3,end:12}]);
assert.equal(rubyEl.textContent,rubySource);assert.equal(marked(rubyEl),'漢字]]<<かんじ');
const rubies=rubyEl.children.flatMap(child=>child.className==='nobreak'?child.children:[child]).filter(child=>child.tag==='ruby');assert.equal(rubies.length,2);
assert.equal(rubies[0].children.find(child=>child.tag==='rt').textContent,'かんじ');
assert.equal(rubies[0].textContent,'漢字]]<<かんじ');
assert.equal(ctx.typesetRuns('[[改行\nは不可]]<<だめ>> [[空]]<<>>').filter(r=>r.kind==='ruby-text').length,0);
const mixed=ctx.typesetRuns('￢⊥[[横]]<<よこ>>￢⊥ [[縦]]<<たて>>');
assert.equal(mixed.find(r=>r.kind==='sideways-text').text,'[[横]]<<よこ>>');assert.equal(mixed.find(r=>r.kind==='ruby-text').text,'たて');
console.log('[[漢字]]<<かんじ>> renders ruby, hides its delimiters, stays on one page, and preserves highlight offsets.');

assert.match(html,/\.page-text \.nobreak\{white-space:nowrap\}/);
const groupText=el=>el.children.filter(child=>child.className==='nobreak').map(child=>child.textContent);
const kinsoku=node();ctx.appendTypeset(kinsoku,'「作って……」と12。「――」[[漢字]]<<かんじ>>」');
assert.equal(kinsoku.textContent,'「作って……」と12。「――」[[漢字]]<<かんじ>>」');
assert.equal(groupText(kinsoku).join('|'),'……」|12。|「――」|[[漢字]]<<かんじ>>」');
const opening=node();ctx.appendTypeset(opening,'彼は「……と言った');assert.equal(groupText(opening).join('|'),'「……');
const plain=node();ctx.appendTypeset(plain,'普通の文章です。');assert.equal(groupText(plain).length,0);
const highlighted=node();ctx.appendTypeset(highlighted,'て……」と',0,[{start:2,end:4}]);assert.equal(marked(highlighted),'…」');
console.log('Line-start/line-end forbidden characters stay attached to symbols, tate-chu-yoko and ruby.');

const rubyOf=el=>{const all=[];const walk=n=>{if(n.tag==='ruby')all.push(n);(n.children||[]).forEach(walk);};walk(el);return all;};
const over=node();ctx.appendTypeset(over,'と[[私]]<<わたくし>>と');const [overRuby]=rubyOf(over);
assert.equal(overRuby.style.marginInlineStart,'-0.473em');assert.equal(overRuby.style.marginInlineEnd,'-0.473em');
const kanji=node();ctx.appendTypeset(kanji,'東[[私]]<<わたくし>>。');assert.equal(rubyOf(kanji)[0].style.marginInlineStart,undefined);assert.equal(rubyOf(kanji)[0].style.marginInlineEnd,undefined);
const short=node();ctx.appendTypeset(short,'の[[欲望]]<<よくぼう>>の');assert.equal(rubyOf(short)[0].style.marginInlineStart,undefined);
console.log('Long ruby overhangs adjacent kana only.');
