const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const {node,document,marked}=require('./text-dom.cjs');
const s=fs.readFileSync(__dirname+'/../dist/index.html','utf8').match(/<script>\n([\s\S]*?)<\/script>/)[1];
const ctx=vm.createContext({document,Intl});vm.runInContext(s.slice(s.indexOf('function sidewaysRanges'),s.indexOf('// Measure actual')),ctx);
const text='「……」――── 12月3日 2026年 Bloom Garden party A組 ... --';
const runs=ctx.typesetRuns(text);assert.equal(runs.map(r=>r.text).join(''),text);
assert.equal(runs.find(r=>r.text==='12').kind,'tcy');
assert.equal(runs.find(r=>r.text==='3').kind,'upright-digits');
assert.equal(runs.find(r=>r.text==='2026').kind,'upright-digits');
assert.equal(runs.find(r=>r.text==='Bloom Garden party').kind,'latin-words');
assert.equal(runs.find(r=>r.text==='A').kind,'latin-single');
assert.equal(runs.find(r=>r.text==='…').kind,'vertical-symbol');
assert.ok(!ctx.boundaries('あ12い').includes(2));
const el=node();ctx.appendTypeset(el,text,0,[{start:2,end:18}]);assert.equal(el.textContent,text);assert.equal(marked(el),text.slice(2,18));
console.log('Vertical typography preserves source text, selection offsets and highlighted numeric/symbol runs.');

const rules=ctx.typesetRuns('前――後');assert.equal(rules.filter(r=>r.kind==='vertical-rule').length,1);assert.equal(rules.find(r=>r.kind==='vertical-rule').text,'――');
const ruleNode=node();ctx.appendTypeset(ruleNode,'――',0,[{start:1,end:2}]);assert.equal(ruleNode.children.length,1);assert.equal(ruleNode.children[0].style.height,'2.11em');assert.equal(ruleNode.textContent,'――');assert.equal(marked(ruleNode),'―');
console.log('Consecutive rules use one continuous drawing box and retain partial highlight offsets.');

const marker='￢⊥',wrapped='前￢⊥安倍晋三￢⊥後',wrappedRuns=ctx.typesetRuns(wrapped);
const html=fs.readFileSync(__dirname+'/../dist/index.html','utf8');
assert.match(html,/\.page-text \.sideways-text\{text-orientation:sideways;-webkit-text-orientation:sideways/);
assert.match(html,/\.page-text \.writing-marker\{display:none!important\}/);
assert.equal(wrappedRuns.map(r=>r.text).join(''),wrapped);
assert.equal(wrappedRuns.filter(r=>r.kind==='writing-marker').map(r=>r.text).join(''),marker+marker);
assert.equal(wrappedRuns.find(r=>r.kind==='sideways-text').text,'安倍晋三');
const wrappedBoundaries=ctx.boundaries(wrapped),openAt=wrapped.indexOf(marker),closeAt=wrapped.lastIndexOf(marker);
assert.ok(!wrappedBoundaries.includes(openAt+1));assert.ok(!wrappedBoundaries.includes(closeAt+1));
assert.ok(wrappedBoundaries.includes(openAt+marker.length+1),'The sideways text can still wrap across pages.');
const wrappedEl=node();ctx.appendTypeset(wrappedEl,wrapped,0,[{start:3,end:7}]);
assert.equal(wrappedEl.textContent,wrapped);assert.equal(marked(wrappedEl),'安倍晋三');
assert.ok(wrappedEl.children.some(child=>child.className==='sideways-text'));
assert.equal(wrappedEl.children.filter(child=>child.className==='writing-marker').length,2);
const partial=wrapped.slice(3,5),partialEl=node();ctx.appendTypeset(partialEl,partial,3,[],wrapped);
assert.equal(partialEl.textContent,partial);assert.equal(partialEl.children[0].className,'sideways-text');
console.log('￢⊥ markers hide their delimiters, rotate enclosed Japanese text, and preserve pagination and highlight offsets.');

const rubySource='前[[漢字]]<<かんじ>>後と[[12月]]<<じゅうにがつ>>',rubyRuns=ctx.typesetRuns(rubySource);
assert.match(html,/\.page-text ruby\{ruby-position:over;ruby-align:space-around\}/);
assert.equal(rubyRuns.map(r=>r.text).join(''),rubySource);
assert.equal(rubyRuns.filter(r=>r.kind==='writing-marker').map(r=>r.text).join('|'),'[[|]]<<|>>|[[|]]<<|>>');
assert.equal(rubyRuns.filter(r=>r.kind==='ruby-text').map(r=>r.text).join('|'),'かんじ|じゅうにがつ');
assert.equal(rubyRuns.find(r=>r.text==='12').kind,'tcy');
const rubyBoundaries=ctx.boundaries(rubySource),rubyStart=rubySource.indexOf('[['),rubyEnd=rubySource.indexOf('>>')+2;
assert.ok(rubyBoundaries.includes(rubyStart)&&rubyBoundaries.includes(rubyEnd));
assert.ok(rubyBoundaries.every(i=>i<=rubyStart||i>=rubyEnd),'Ruby is never split across pages.');
const rubyEl=node();ctx.appendTypeset(rubyEl,rubySource,0,[{start:3,end:12}]);
assert.equal(rubyEl.textContent,rubySource);assert.equal(marked(rubyEl),'漢字]]<<かんじ');
const rubies=rubyEl.children.flatMap(child=>child.className==='nobreak'?child.children:[child]).filter(child=>child.tag==='ruby');assert.equal(rubies.length,2);
assert.equal(rubies[0].children.find(child=>child.tag==='rt').textContent,'かんじ');
assert.equal(rubies[0].textContent,'漢字]]<<かんじ');
assert.equal(ctx.typesetRuns('[[改行\nは不可]]<<だめ>> [[空]]<<>>').filter(r=>r.kind==='ruby-text').length,0);
const mixed=ctx.typesetRuns('￢⊥[[横]]<<よこ>>￢⊥ [[縦]]<<たて>>');
assert.equal(mixed.find(r=>r.kind==='sideways-text').text,'[[横]]<<よこ>>');assert.equal(mixed.find(r=>r.kind==='ruby-text').text,'たて');
console.log('[[漢字]]<<かんじ>> renders ruby, hides its delimiters, stays on one page, and preserves highlight offsets.');

assert.match(html,/\.page-text \.nobreak\{white-space:nowrap\}/);
const groupText=el=>el.children.filter(child=>child.className==='nobreak').map(child=>child.textContent);
const kinsoku=node();ctx.appendTypeset(kinsoku,'「作って……」と12。「――」[[漢字]]<<かんじ>>」');
assert.equal(kinsoku.textContent,'「作って……」と12。「――」[[漢字]]<<かんじ>>」');
assert.equal(groupText(kinsoku).join('|'),'……」|12。|「――」|[[漢字]]<<かんじ>>」');
const opening=node();ctx.appendTypeset(opening,'彼は「……と言った');assert.equal(groupText(opening).join('|'),'「……');
const plain=node();ctx.appendTypeset(plain,'普通の文章です。');assert.equal(groupText(plain).length,0);
const highlighted=node();ctx.appendTypeset(highlighted,'て……」と',0,[{start:2,end:4}]);assert.equal(marked(highlighted),'…」');
console.log('Line-start/line-end forbidden characters stay attached to symbols, tate-chu-yoko and ruby.');

const rubyOf=el=>{const all=[];const walk=n=>{if(n.tag==='ruby')all.push(n);(n.children||[]).forEach(walk);};walk(el);return all;};
const over=node();ctx.appendTypeset(over,'と[[私]]<<わたくし>>と');const [overRuby]=rubyOf(over);
assert.equal(overRuby.style.marginInlineStart,'-0.473em');assert.equal(overRuby.style.marginInlineEnd,'-0.473em');
const kanji=node();ctx.appendTypeset(kanji,'東[[私]]<<わたくし>>。');assert.equal(rubyOf(kanji)[0].style.marginInlineStart,undefined);assert.equal(rubyOf(kanji)[0].style.marginInlineEnd,undefined);
const short=node();ctx.appendTypeset(short,'の[[欲望]]<<よくぼう>>の');assert.equal(rubyOf(short)[0].style.marginInlineStart,undefined);
console.log('Long ruby overhangs adjacent kana only.');

assert.match(html,/<form id="edit-form">[\s\S]*?<button type="button" id="markup-link" class="link-button">原文のマークダウン記法<\/button>[\s\S]*?<\/form><\/dialog><dialog id="markup-dialog"/);
assert.doesNotMatch(html,/shelf-footer|markup-view/);
const samples=[...html.matchAll(/data-sample="([^"]*)"/g)].map(m=>m[1].replace(/&lt;/g,'<').replace(/&gt;/g,'>'));
assert.equal(samples.length,5);
for(const sample of samples){const sampleEl=node();ctx.appendTypeset(sampleEl,sample);assert.equal(sampleEl.textContent,sample);}
assert.ok(ctx.typesetRuns(samples[0]).some(r=>r.kind==='ruby-text'));assert.ok(ctx.typesetRuns(samples[1]).some(r=>r.kind==='sideways-text'));assert.ok(ctx.typesetRuns(samples[2]).some(r=>r.kind==='upright-text'));assert.ok(ctx.typesetRuns(samples[3]).some(r=>r.deco==='md-bold'));assert.ok(ctx.typesetRuns(samples[4]).some(r=>r.deco==='md-strike'));
console.log('The source editor links to the markup guide, and its examples use the real syntax.');

assert.match(html,/\.page-text \.upright-text\{text-orientation:upright;-webkit-text-orientation:upright/);
const upSource='発表は⊥⊥WHO⊥⊥と⊥⊥UNICEF⊥⊥。',upRuns=ctx.typesetRuns(upSource);
assert.equal(upRuns.map(r=>r.text).join(''),upSource);
assert.equal(upRuns.filter(r=>r.kind==='upright-text').map(r=>r.text).join('|'),'WHO|UNICEF');
assert.equal(upRuns.filter(r=>r.kind==='writing-marker').length,4);assert.ok(!upRuns.some(r=>r.kind==='latin-words'));
const upEdges=ctx.boundaries(upSource),upStart=upSource.indexOf('⊥⊥'),upEnd=upSource.indexOf('⊥⊥',upStart+2)+2;
assert.ok(upEdges.every(i=>i<=upStart||i>=upEnd),'Upright text stays on one page.');
const upEl=node();ctx.appendTypeset(upEl,upSource,0,[{start:6,end:8}]);assert.equal(upEl.textContent,upSource);assert.equal(marked(upEl),'HO');
assert.equal(upEl.children.filter(c=>c.className==='nobreak').map(c=>c.textContent).join('|'),'⊥⊥WHO⊥⊥|⊥⊥UNICEF⊥⊥。');
const kind=t=>ctx.typesetRuns(t).filter(r=>r.kind==='upright-text'||r.kind==='sideways-text').map(r=>r.kind+':'+r.text).join('|');
assert.equal(kind('￢⊥横￢⊥⊥⊥NHK⊥⊥'),'sideways-text:横|upright-text:NHK');
assert.equal(kind('⊥⊥⊥⊥ ⊥⊥改\n行⊥⊥ ⊥⊥閉じない'),'');
console.log('⊥⊥ markers keep abbreviations upright on one line and coexist with ￢⊥.');

assert.match(html,/\.page-text \.md-bold\{font-weight:700\}\.page-text \.md-strike\{text-decoration:line-through/);
const decoText=t=>ctx.typesetRuns(t).filter(r=>r.deco).map(r=>r.deco+':'+r.text).join('|');
const bs='それは**とても大切な**約束で~~嘘~~本当だ。';
assert.equal(ctx.typesetRuns(bs).map(r=>r.text).join(''),bs);
assert.equal(ctx.typesetRuns(bs).filter(r=>r.kind==='writing-marker').map(r=>r.text).join('|'),'**|**|~~|~~');
assert.equal(decoText(bs),'md-bold:とても大切な|md-strike:嘘');
assert.equal(decoText('**12月の[[約束]]<<やくそく>>**'),'md-bold:12|md-bold:月の|md-bold:約束|md-bold:やくそく');
assert.equal(decoText('**太~~両方~~太**'),'md-bold:太|md-bold md-strike:両方|md-bold:太');
assert.equal(decoText('彼は~~嘘~~本当と~~……~~と**~~両方~~**。'),'md-strike:嘘|md-strike:…|md-strike:…|md-bold md-strike:両方');
assert.equal(decoText('**改\n行** ** ** ****  ~~〜~~ 〜〜x〜〜 ～～y～～ [[a**b]]<<c**>>'),'md-strike:〜');
const bsEl=node();ctx.appendTypeset(bsEl,bs,0,[{start:6,end:10}]);assert.equal(bsEl.textContent,bs);assert.equal(marked(bsEl),'ても大切');
assert.ok(bsEl.children.some(c=>c.className==='md-bold'));assert.ok(bsEl.children.some(c=>c.className==='md-strike'&&c.textContent==='嘘'));
const tcyBold=node();ctx.appendTypeset(tcyBold,'**12**');assert.ok(tcyBold.children.some(c=>c.className==='tcy md-bold'));
const glued=node();ctx.appendTypeset(glued,'て**……**」と');assert.equal(glued.children.filter(c=>c.className==='nobreak').map(c=>c.textContent).join('|'),'……**」');
console.log('** and ~~ add bold and strikethrough, wrap other markup, and keep kinsoku across hidden markers.');

assert.match(html,/<div class="view-toggle" role="group" aria-label="本棚の表示"><button type="button" id="view-grid" data-view="grid"[^>]*aria-label="グリッド表示"[\s\S]*?id="view-list" data-view="list"[^>]*aria-label="リスト表示"/);
assert.match(html,/@media\(max-width:680px\)\{\.shelf-grid\.view-grid\{grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/);
assert.match(html,/function shelfView\(\)\{return settings\.shelfView==='list'\?'list':'grid';\}/);
console.log('The library offers a remembered grid/list toggle with three covers per row on phones.');
assert.match(html,/card\.onclick=e=>\{if\(shelfView\(\)==='list'&&!e\.target\.closest\('button'\)\)open\(\);\};/);
console.log('In list view, the whole row except its buttons opens the book.');
